//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.15 at 03:32:45 PM EDT 
//


package analytics.livestream.livestream_api.channel_api._2;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.livestream.channel.api._2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _IsPremium_QNAME = new QName("http://api.channel.livestream.com/2.0", "isPremium");
    private final static QName _TotalLibraryRecordings_QNAME = new QName("http://api.channel.livestream.com/2.0", "totalLibraryRecordings");
    private final static QName _ViewerMinutesThisWeek_QNAME = new QName("http://api.channel.livestream.com/2.0", "viewerMinutesThisWeek");
    private final static QName _ShortName_QNAME = new QName("http://api.channel.livestream.com/2.0", "shortName");
    private final static QName _TotalLibraryClips_QNAME = new QName("http://api.channel.livestream.com/2.0", "totalLibraryClips");
    private final static QName _ViewerMinutesToday_QNAME = new QName("http://api.channel.livestream.com/2.0", "viewerMinutesToday");
    private final static QName _CurrentViewerCount_QNAME = new QName("http://api.channel.livestream.com/2.0", "currentViewerCount");
    private final static QName _TotalViewerMinutes_QNAME = new QName("http://api.channel.livestream.com/2.0", "totalViewerMinutes");
    private final static QName _IsLive_QNAME = new QName("http://api.channel.livestream.com/2.0", "isLive");
    private final static QName _Tags_QNAME = new QName("http://api.channel.livestream.com/2.0", "tags");
    private final static QName _ViewerMinutesThisMonth_QNAME = new QName("http://api.channel.livestream.com/2.0", "viewerMinutesThisMonth");
    private final static QName _Links_QNAME = new QName("http://api.channel.livestream.com/2.0", "links");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.livestream.channel.api._2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PromoUrl }
     * 
     */
    public PromoUrl createPromoUrl() {
        return new PromoUrl();
    }

    /**
     * Create an instance of {@link Profile }
     * 
     */
    public Profile createProfile() {
        return new Profile();
    }

    /**
     * Create an instance of {@link BannerUrl }
     * 
     */
    public BannerUrl createBannerUrl() {
        return new BannerUrl();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.channel.livestream.com/2.0", name = "isPremium")
    public JAXBElement<Boolean> createIsPremium(Boolean value) {
        return new JAXBElement<Boolean>(_IsPremium_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.channel.livestream.com/2.0", name = "totalLibraryRecordings")
    public JAXBElement<BigInteger> createTotalLibraryRecordings(BigInteger value) {
        return new JAXBElement<BigInteger>(_TotalLibraryRecordings_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.channel.livestream.com/2.0", name = "viewerMinutesThisWeek")
    public JAXBElement<BigInteger> createViewerMinutesThisWeek(BigInteger value) {
        return new JAXBElement<BigInteger>(_ViewerMinutesThisWeek_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.channel.livestream.com/2.0", name = "shortName")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createShortName(String value) {
        return new JAXBElement<String>(_ShortName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.channel.livestream.com/2.0", name = "totalLibraryClips")
    public JAXBElement<BigInteger> createTotalLibraryClips(BigInteger value) {
        return new JAXBElement<BigInteger>(_TotalLibraryClips_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.channel.livestream.com/2.0", name = "viewerMinutesToday")
    public JAXBElement<BigInteger> createViewerMinutesToday(BigInteger value) {
        return new JAXBElement<BigInteger>(_ViewerMinutesToday_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.channel.livestream.com/2.0", name = "currentViewerCount")
    public JAXBElement<BigInteger> createCurrentViewerCount(BigInteger value) {
        return new JAXBElement<BigInteger>(_CurrentViewerCount_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.channel.livestream.com/2.0", name = "totalViewerMinutes")
    public JAXBElement<BigInteger> createTotalViewerMinutes(BigInteger value) {
        return new JAXBElement<BigInteger>(_TotalViewerMinutes_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.channel.livestream.com/2.0", name = "isLive")
    public JAXBElement<Boolean> createIsLive(Boolean value) {
        return new JAXBElement<Boolean>(_IsLive_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.channel.livestream.com/2.0", name = "tags")
    public JAXBElement<String> createTags(String value) {
        return new JAXBElement<String>(_Tags_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.channel.livestream.com/2.0", name = "viewerMinutesThisMonth")
    public JAXBElement<BigInteger> createViewerMinutesThisMonth(BigInteger value) {
        return new JAXBElement<BigInteger>(_ViewerMinutesThisMonth_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.channel.livestream.com/2.0", name = "links")
    public JAXBElement<String> createLinks(String value) {
        return new JAXBElement<String>(_Links_QNAME, String.class, null, value);
    }

}
