//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.15 at 03:32:45 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://api.channel.livestream.com/2.0")
package analytics.livestream.livestream_api.channel_api._2;
